const express = require('express')
const app = express()
const cors = require('cors')
const connectMongo = require('./db')
app.use(express.json())
require('dotenv').config()
app.use(cors())
connectMongo()
app.use('/api/auth', require('./routes/auth'))
app.use('/api/blog', require('./routes/blog'))
app.use('/api/news', require('./routes/news'))

app.listen(process.env.PORT || 5000, () => {
  console.log(`app listening to http://localhost:5000`)
})
