name: Deploy Client to S3 & CloudFront

on:
  push:
    paths:
      - 'client/**'   # Runs only if changes happen inside "client" folder
    branches:
      - main          # Change to your deployment branch

jobs:
  build-and-deploy:
    name: Build and Deploy  
    runs-on: ubuntu-latest
    env:
      BUCKET: news-client
      DIST: build
      REGION: ap-south-1
      DIST_ID: E1A69R981GMVCD
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18   # Change based on your project

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          
      - name: Install Dependencies
        run: |
          cd client
          npm install   # Use yarn if needed

      - name: Build Client
        run: |
          cd client
          npm run build   # Adjust based on your build command

      - name: Deploy to S3
        run: aws s3 sync client/dist s3://${{env.BUCKET}} --delete
        
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{env.DIST_ID}} --paths "/*"
        
